#!/usr/bin/env bash
# build.sh — generated by paper-covert
# Builds the submission PDF from latex/main.tex.
#
# Venue: {{VENUE}}
# Engine: {{BUILD_ENGINE}}
# Bibliography engine: {{BIB_ENGINE}}

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

ENGINE="${ENGINE:-{{BUILD_ENGINE}}}"
BIB_ENGINE="${BIB_ENGINE:-{{BIB_ENGINE}}}"

if command -v latexmk >/dev/null 2>&1 && [ "$ENGINE" = "latexmk" ]; then
    latexmk -C main >/dev/null 2>&1 || true
    latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex
elif command -v xelatex >/dev/null 2>&1 && [ "$ENGINE" = "xelatex" ]; then
    xelatex -interaction=nonstopmode -halt-on-error main.tex
    "$BIB_ENGINE" main || true
    xelatex -interaction=nonstopmode -halt-on-error main.tex
    xelatex -interaction=nonstopmode -halt-on-error main.tex
else
    pdflatex -interaction=nonstopmode -halt-on-error main.tex
    "$BIB_ENGINE" main || true
    pdflatex -interaction=nonstopmode -halt-on-error main.tex
    pdflatex -interaction=nonstopmode -halt-on-error main.tex
fi

# Copy the final PDF up into the submission pdf/ folder.
mkdir -p "../pdf"
cp -f main.pdf "../pdf/MANUSCRIPT_SUBMISSION_READY.pdf"

# Summarize warnings.
{
  echo "# PDF build summary"
  echo
  echo "- Engine: $ENGINE"
  echo "- Pages: $(pdfinfo main.pdf 2>/dev/null | awk '/^Pages:/ {print $2}')"
  echo "- Overfull hbox: $(grep -c 'Overfull' main.log || echo 0)"
  echo "- Underfull hbox: $(grep -c 'Underfull' main.log || echo 0)"
  echo "- Undefined references: $(grep -c 'undefined reference' main.log || echo 0)"
  echo "- Undefined citations: $(grep -c 'undefined citation' main.log || echo 0)"
} > BUILD_NOTES.md
